/**
 * Texture lookup for effects. Shared particle textures (TextureKeys.TEX) are
 * generated by the render agent at boot; if one is missing at runtime we
 * paint an equivalent fallback on a canvas under a separate `fx_fb_*` key so
 * effects never crash or render the missing-texture placeholder.
 * Also owns the effect-only textures (vignette, flat white).
 */
import type * as Phaser from 'phaser';
import { TEX } from '../TextureKeys';

export const FX_TEX = {
  vignette: 'fx_vignette',
  white: 'fx_white',
} as const;

type Painter = { w: number; h: number; paint: (g: CanvasRenderingContext2D, w: number, h: number) => void };

const PAINTERS: Record<string, Painter> = {
  [TEX.pixel]: { w: 8, h: 8, paint: (g, w, h) => fill(g, w, h) },
  [TEX.soft]: {
    w: 32,
    h: 32,
    paint: (g, w) => radial(g, w, [
      [0, 1],
      [0.35, 0.75],
      [0.7, 0.25],
      [1, 0],
    ]),
  },
  [TEX.dot]: {
    w: 16,
    h: 16,
    paint: (g, w) => {
      g.fillStyle = '#fff';
      g.beginPath();
      g.arc(w / 2, w / 2, w / 2 - 0.5, 0, Math.PI * 2);
      g.fill();
    },
  },
  [TEX.sliver]: {
    w: 12,
    h: 4,
    paint: (g, w, h) => {
      g.fillStyle = '#fff';
      g.beginPath();
      g.moveTo(0, h / 2);
      g.lineTo(2, 0.3);
      g.lineTo(w - 1, h * 0.35);
      g.lineTo(w, h / 2);
      g.lineTo(w - 1, h * 0.65);
      g.lineTo(2, h - 0.3);
      g.closePath();
      g.fill();
    },
  },
  [TEX.shard]: {
    w: 10,
    h: 10,
    paint: (g, w, h) => {
      g.fillStyle = '#fff';
      g.beginPath();
      g.moveTo(w * 0.5, 0.5);
      g.lineTo(w - 0.5, h - 1);
      g.lineTo(0.5, h * 0.8);
      g.closePath();
      g.fill();
    },
  },
  [TEX.ring]: {
    w: 64,
    h: 64,
    paint: (g, w) => {
      g.strokeStyle = 'rgba(255,255,255,0.35)';
      g.lineWidth = 6;
      g.beginPath();
      g.arc(w / 2, w / 2, w / 2 - 5, 0, Math.PI * 2);
      g.stroke();
      g.strokeStyle = '#fff';
      g.lineWidth = 2.5;
      g.beginPath();
      g.arc(w / 2, w / 2, w / 2 - 5, 0, Math.PI * 2);
      g.stroke();
    },
  },
  [TEX.glow]: {
    w: 64,
    h: 64,
    paint: (g, w) => radial(g, w, [
      [0, 1],
      [0.15, 0.85],
      [0.4, 0.35],
      [0.7, 0.08],
      [1, 0],
    ]),
  },
  [TEX.bolt]: {
    w: 10,
    h: 10,
    paint: (g, w) => {
      g.fillStyle = '#222';
      g.beginPath();
      g.arc(w / 2, w / 2, w / 2, 0, Math.PI * 2);
      g.fill();
      g.fillStyle = '#fff';
      g.beginPath();
      g.arc(w / 2, w / 2, w / 2 - 1.5, 0, Math.PI * 2);
      g.fill();
    },
  },
  [FX_TEX.white]: { w: 4, h: 4, paint: (g, w, h) => fill(g, w, h) },
  [FX_TEX.vignette]: {
    w: 256,
    h: 256,
    paint: (g, w) => {
      const c = w / 2;
      const grad = g.createRadialGradient(c, c, w * 0.22, c, c, w * 0.72);
      grad.addColorStop(0, 'rgba(255,255,255,0)');
      grad.addColorStop(0.45, 'rgba(255,255,255,0.18)');
      grad.addColorStop(0.8, 'rgba(255,255,255,0.62)');
      grad.addColorStop(1, 'rgba(255,255,255,1)');
      g.fillStyle = grad;
      g.fillRect(0, 0, w, w);
    },
  },
};

function fill(g: CanvasRenderingContext2D, w: number, h: number): void {
  g.fillStyle = '#fff';
  g.fillRect(0, 0, w, h);
}

function radial(g: CanvasRenderingContext2D, w: number, stops: [number, number][]): void {
  const c = w / 2;
  const grad = g.createRadialGradient(c, c, 0, c, c, c);
  for (const [o, a] of stops) grad.addColorStop(o, `rgba(255,255,255,${a})`);
  g.fillStyle = grad;
  g.fillRect(0, 0, w, w);
}

function paint(scene: Phaser.Scene, key: string, painter: Painter): boolean {
  const tex = scene.textures.createCanvas(key, painter.w, painter.h);
  if (!tex) return false;
  const ctx = tex.getContext();
  ctx.clearRect(0, 0, painter.w, painter.h);
  painter.paint(ctx, painter.w, painter.h);
  tex.refresh();
  return true;
}

function usable(scene: Phaser.Scene, key: string): boolean {
  if (!scene.textures.exists(key)) return false;
  const frame = scene.textures.getFrame(key);
  return !!frame && frame.width > 0 && frame.height > 0;
}

/**
 * Return a usable texture key for `key`: the shared one if it exists,
 * otherwise a locally painted fallback (created once).
 */
export function resolveTexture(scene: Phaser.Scene, key: string): string {
  if (usable(scene, key)) return key;
  const fb = `fx_fb_${key}`;
  if (usable(scene, fb)) return fb;
  const painter = PAINTERS[key] ?? PAINTERS[TEX.soft]!;
  return paint(scene, fb, painter) ? fb : '__WHITE';
}

/** Create the effect-only textures if needed. */
export function ensureFxTextures(scene: Phaser.Scene): void {
  for (const key of [FX_TEX.white, FX_TEX.vignette]) {
    if (!usable(scene, key)) paint(scene, key, PAINTERS[key]!);
  }
}
